"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ProductService_1 = require("./ProductService");
var Product_1 = require("./Product");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getProducts();
// result = _productService.getById(2);
var p = new Product_1.Product();
p.name = 'Apple IPhone 6';
p.price = 3000;
p.category = 'Phone';
// _productService.saveProduct(p);
// _productService.deleteProduct(_productService.getById(2));
var p1 = new Product_1.Product();
p1.id = 3;
p1.name = 'Apple IPhone x';
p1.price = 10000;
p1.category = 'Phone';
_productService.saveProduct(p1);
console.log(result);
